# Generated by Django 4.0.2 on 2022-03-13 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prosumer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('id', models.TextField(max_length=39, primary_key=True, serialize=False, unique=True)),
                ('max_import_power', models.FloatField()),
                ('max_export_power', models.FloatField()),
                ('is_online', models.BooleanField()),
                ('is_trader', models.BooleanField()),
                ('is_dr_adaptive', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProsumerEnergyStorageSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('is_online', models.BooleanField()),
                ('dr_adaptive', models.BooleanField()),
                ('max_capacity', models.FloatField()),
                ('usable_capacity', models.FloatField()),
                ('max_charge_rate', models.FloatField()),
                ('max_discharge_rate', models.FloatField()),
                ('type', models.TextField()),
                ('prosumer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mgems.prosumer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProsumerEnergyGenerationSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('is_online', models.BooleanField()),
                ('max_power', models.FloatField()),
                ('is_renewable', models.BooleanField()),
                ('type', models.TextField()),
                ('efficiency', models.FloatField()),
                ('prosumer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mgems.prosumer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProsumerEnergyConsumptionSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('is_online', models.BooleanField()),
                ('dr_adaptive', models.BooleanField()),
                ('max_power', models.FloatField()),
                ('prosumer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mgems.prosumer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
