# Generated by Django 4.0.2 on 2022-04-13 03:51

from django.db import migrations, models
import django.db.models.deletion
import mgems.models


class Migration(migrations.Migration):

    dependencies = [
        ('mgems', '0002_remove_prosumerenergyconsumptionsystem_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosumer',
            name='id',
            field=mgems.models.ProsumerID(max_length=39, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='AtomicTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField()),
                ('energy_consumed', models.FloatField()),
                ('transmission_losses', models.FloatField()),
                ('unit_market_price', models.FloatField()),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumer_of_transaction', to='mgems.prosumer')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producer_of_transaction', to='mgems.prosumer')),
            ],
        ),
    ]
