version: '3.9'

networks:
  vaidyuti_public_if: {}
  vaidyuti_internal_if: {}

services:
  # VerneMQ MQTT Server
  vernemq:
    image: vernemq/vernemq
    restart: always
    ports:
      - 1883:1883
    environment:
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on # Disabled for testing
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
    networks:
      - vaidyuti_internal_if
      - vaidyuti_public_if

  influxdb:
    image: influxdb:2.1.1
    restart: always
    ports:
      - 8086:8086
    volumes:
      # Mount for influxdb data directory and configuration
      - ./data/influx-v2:/var/lib/influxdb2:rw
    networks:
      - vaidyuti_internal_if
  
  telegraf:
    image: telegraf
    restart: always
    volumes:
      - ./data/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - INFLUX_HOST=http://influxdb:8086
      - INFLUX_ORG=Vaidyuti
      - INFLUX_TOKEN=fNrGfCAk6gSLjerPosqf_p8_mqanWnxOB77TD2tYFyw2evPvF-GcDHGHQKtTzOnPiBZf1ders_voukxoPendKQ==
      - INFLUX_BUCKET=bucket2
    depends_on:
      - vernemq-mqtt-broker
      - influxdb
    networks:
      - vaidyuti_internal_if
      - vaidyuti_public_if

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - influxdb
    networks:
      - vaidyuti_internal_if
      - vaidyuti_public_if