version: '3.9'

networks:
  public:
    name: vaidyuti-public

  internal:
    name: vaidyuti-internal

services:
  # VerneMQ MQTT Server
  vernemq:
    image: vernemq/vernemq
    restart: always
    ports:
      - 1883:1883
    environment:
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on # Disabled for testing
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
    networks:
      - internal
      - public

  influxdb:
    image: influxdb:2.1.1
    restart: always
    ports:
      - 8086:8086
    volumes:
      # Mount for influxdb data directory and configuration
      - ./data/influx-v2:/var/lib/influxdb2:rw
    networks:
      - internal

  telegraf:
    image: telegraf
    restart: always
    volumes:
      - ./data/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - INFLUX_HOST=http://influxdb:8086
      - INFLUX_ORG=Vaidyuti
      - INFLUX_TOKEN=7QE8qsJhrOmC8S4QSIb1oC2hd8P9v0okhYh6dYvd-UFs0dAYltHDB4VJir5B01WZnKdQJa7TPL1yVt97M6SQ-A==
      - INFLUX_BUCKET=central
    depends_on:
      - vernemq-mqtt-broker
      - influxdb
    networks:
      - internal
      - public

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      GF_SERVER_PROTOCOL: "http"
      GF_SERVER_DOMAIN: "vaidyuti.ddns.net"
      GF_SERVER_METRICS_ENABLED: "true"
      GF_SERVER_METRICS_INTERVAL_SECONDS: "10"
    depends_on:
      - influxdb
    networks:
      - internal
      - public
