version: '3.9'

networks:
  public:
    name: vaidyuti-public

  internal:
    name: vaidyuti-internal

services:
  emqx:
    image: emqx/emqx:4.4.2
    restart: always
    ports:
      - 1883:1883
      - 8081:8081
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
    networks:
      - internal
      - public

  influxdb:
    image: influxdb:2.1.1
    restart: always
    ports:
      - 8086:8086
    volumes:
      - ./data/influx-v2:/var/lib/influxdb2:rw
    networks:
      - internal

  telegraf:
    image: telegraf
    restart: always
    volumes:
      - ./data/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - MQTT_SERVER=tcp://emqx:1883
      - INFLUX_HOST=http://influxdb:8086
      - INFLUX_ORG=Vaidyuti
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
    depends_on:
      - emqx
      - influxdb
    networks:
      - internal
      - public

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
