version: '3.9'


services:
  # VerneMQ MQTT Server
  vernemq:
    container_name: vernemq-mqtt-broker
    image: vernemq/vernemq
    restart: always
    ports:
      - 1883:1883
    environment:
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on # Disabled for testing
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes

  influxdb:
    container_name: influxdb
    image: influxdb:2.1.1
    restart: always
    ports:
      - 8086:8086
    volumes:
      # Mount for influxdb data directory and configuration
      - ./influx-v2:/var/lib/influxdb2:rw
  
  telegraf:
    container_name: telegraf-aggregator
    image: telegraf
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - INFLUX_HOST=http://influxdb:8086
      - INFLUX_ORG=Vaidyuti
      - INFLUX_TOKEN=fNrGfCAk6gSLjerPosqf_p8_mqanWnxOB77TD2tYFyw2evPvF-GcDHGHQKtTzOnPiBZf1ders_voukxoPendKQ==
      - INFLUX_BUCKET=bucket2
    depends_on:
      - vernemq-mqtt-broker
      - influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - influxdb