version: '3.9'


services:
  # VerneMQ MQTT Server
  vernemq:
    container_name: vernemq-mqtt-broker
    image: vernemq/vernemq
    restart: always
    ports:
      - 1883:1883
    environment:
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on # Disabled for testing
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes

  influxdb:
    container_name: influxdb
    image: influxdb:2.1.1
    restart: always
    ports:
      - 8086:8086
    volumes:
      # Mount for influxdb data directory and configuration
      - ./influx-v2:/var/lib/influxdb2:rw
 