version: '3.9'


services:
  # VerneMQ MQTT Server
  vernemq:
    container_name: test_vernemq_instance
    image: vernemq/vernemq
    environment:
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on # Disabled for testing
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
    ports:
      - 1883:1883
