name: Smart Meter Firmware Checks

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
      

jobs:
  compile_sketch:
    runs-on: ubuntu-latest
    steps:
      - name: Compile Arduino Sketches
        uses: arduino/compile-sketches@v1.0.0
        with:
          fqbn: 'arduino:avr:uno'
          libraries: |
            - name: Servo
            - name: Stepper
              version: 1.1.3
