name: Smart Meter Firmware CI CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
env:

jobs:
  compile_sketch:
    runs-on: ubuntu-latest
    steps:
      - name: Compile Arduino Sketches
        uses: arduino/compile-sketches@v1.0.0
        with:
        fqbn: 'arduino:avr:uno'
        libraries: |
          - name: Servo
          - name: Stepper
            version: 1.1.3
© 2022 GitHub, Inc.
Terms
